<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="1" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="94" started-at="2017-06-04T15:52:16Z" finished-at="2017-06-04T15:52:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="94" started-at="2017-06-04T15:52:16Z" finished-at="2017-06-04T15:52:16Z">
      <class name="classTest.annotationTest">
        <test-method status="PASS" signature="logInTest()[pri:1, instance:classTest.annotationTest@59f99ea]" name="logInTest" duration-ms="16" started-at="2017-06-04T11:52:16Z" finished-at="2017-06-04T11:52:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInTest -->
        <test-method status="PASS" signature="changePasswordTest()[pri:2, instance:classTest.annotationTest@59f99ea]" name="changePasswordTest" duration-ms="0" started-at="2017-06-04T11:52:16Z" depends-on-methods="classTest.annotationTest.logInTest" finished-at="2017-06-04T11:52:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePasswordTest -->
        <test-method status="SKIP" signature="skipTest()[pri:4, instance:classTest.annotationTest@59f99ea]" name="skipTest" duration-ms="18" started-at="2017-06-04T11:52:16Z" finished-at="2017-06-04T11:52:16Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Function is not delivered by Dev Yet]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Function is not delivered by Dev Yet
	at classTest.annotationTest.skipTest(annotationTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipTest -->
        <test-method status="PASS" signature="logOutTest()[pri:3, instance:classTest.annotationTest@59f99ea]" name="logOutTest" duration-ms="0" started-at="2017-06-04T11:52:16Z" finished-at="2017-06-04T11:52:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutTest -->
      </class> <!-- classTest.annotationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
